column_type:
  amount: float
  date: date
  name: str
currency_conversion:
  from: EUR
  to: USD
currency_rate: 1.6
date_format: '%Y-%d-%m'
output_currency_symbol: $
required_column:
- name
- date
- amount
required_output_format: json
